services:
  postgres:
    image: postgres:15
    container_name: userdb
    environment:
      POSTGRES_DB: userdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - user-network

  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - user-network
    volumes:
      - pgadmin_data:/var/lib/pgadmin

  tomcat:
    build: .
    container_name: user-management-app
    depends_on:
      - postgres
    ports:
      - "8081:8080"
    networks:
      - user-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  user-network: